[agencies.ns]
name = "Nederlandse Spoorwegen"
abbr = "NS"

[stations]
rtd = {name = "Rotterdam Centraal", node = true}
rtda = {name = "Rotterdam Alexander"}
gd = {name = "Gouda", node = true}
ut = {name = "Utrecht Centraal", node = true}
amf = {name = "Amersfoort Centraal", node = true}
zl = {name = "Zwolle", node = true}
asn = {name = "Assen"}
gn = {name = "Groningen"}

[train_types.ic]
name = "Intercity"
abbr = "IC"

[train_series.500]
agency = "ns"
type = "ic"
name = "IC 500 Rotterdam Centraal - Leeuwarden"
abbr = "500"

[train_series.500.route]
0 = {type = 'begin', station = "rtd", dep = "00:05"}
1 = {type = 'stop', station = "rtda", arr = "00:12", dep = "00:13"}
2 = {type = 'stop', station = "gd", arr = "00:23", dep = "00:24"}
3 = {type = 'stop', station = "ut", arr = "00:42", dep = "00:49"}
4 = {type = 'stop', station = "amf", arr = "01:02", dep = "01:04"}
5 = {type = 'stop', station = "zl", arr = "01:39", dep = "01:45"}
6 = {type = 'stop', station = "asn", arr = "02:24", dep = "02:25"}
7 = {type = 'end', station = "gn", arr = "02:42"}

[trains]
515 = {series = "500", time = "05:00", begin_at_point = "5"}
519 = {series = "500", time = "06:00"}
523 = {series = "500", time = "07:00"}
527 = {series = "500", time = "08:00"}
531 = {series = "500", time = "09:00"}
535 = {series = "500", time = "10:00"}
539 = {series = "500", time = "11:00"}
543 = {series = "500", time = "12:00"}
547 = {series = "500", time = "13:00"}
551 = {series = "500", time = "14:00"}
555 = {series = "500", time = "15:00"}
559 = {series = "500", time = "16:00"}
563 = {series = "500", time = "17:00"}
567 = {series = "500", time = "18:00"}
571 = {series = "500", time = "19:00"}
575 = {series = "500", time = "20:00"}
579 = {series = "500", time = "21:00"}
583 = {series = "500", time = "22:00"}
587 = {series = "500", time = "23:00"}
591 = {series = "500", time = "24:00", ends_at_point = "4"}
