# Feed-informatie
feed_id = "nl_ns_500"
feed_name = "NS serie 500"
feed_author = "Danae"


# Definities van vervoerders
[agencies.nl_ns]
name = "Nederlandse Spoorwegen"
abbr = "NS"


# Definities van stations
[nodes]
nl_rtd = {name = "Rotterdam Centraal", node = true, train_types = ["nl_ic", "nl_spr"]}
nl_rtda = {name = "Rotterdam Alexander", train_types = ["nl_ic", "nl_spr"]}
nl_gd = {name = "Gouda", node = true, train_types = ["nl_ic", "nl_spr"]}
nl_ut = {name = "Utrecht Centraal", node = true, train_types = ["nl_ic", "nl_spr"]}
nl_amf = {name = "Amersfoort Centraal", node = true, train_types = ["nl_ic", "nl_spr"]}
nl_zl = {name = "Zwolle", node = true, train_types = ["nl_ic", "nl_spr"]}
nl_asn = {name = "Assen", train_types = ["nl_ic", "nl_spr"]}
nl_gn = {name = "Groningen", node = true, train_types = ["nl_ic", "nl_spr"]}


# Definities van vervoerswijzen (treintypes)
[modalities]
nl_ic = {name = "Intercity", abbr = "IC", priority = 1}
nl_spr = {name = "Sprinter", abbr = "SPR", priority = 2}


# Definities van routes (treinseries)
[routes.nl_500]
agency = "nl_ns"
modality = "nl_ic"
name = "IC 500 Rotterdam Centraal - Leeuwarden"
abbr = "500"

[routes.nl_500.stops]
00 = {node = "nl_rtd", d = "00:05"}
01 = {node = "nl_rtda", a = "00:12", d = "00:13"}
02 = {node = "nl_gd", a = "00:23", d = "00:24"}
03 = {node = "nl_ut", a = "00:42", d = "00:49"}
04 = {node = "nl_amf", a = "01:02", d = "01:04"}
05 = {node = "nl_zl", a = "01:39", d = "01:45"}
06 = {node = "nl_asn", a = "02:24", d = "02:25"}
07 = {node = "nl_gn", a = "02:42"}


# Definities van trips (afzonderlijke treinen)
[trips]
nl_515 = {route = "500", time = "05:00", begin_at = "nl_zl"}
nl_519 = {route = "500", time = "06:00"}
nl_523 = {route = "500", time = "07:00"}
nl_527 = {route = "500", time = "08:00"}
nl_531 = {route = "500", time = "09:00"}
nl_535 = {route = "500", time = "10:00"}
nl_539 = {route = "500", time = "11:00"}
nl_543 = {route = "500", time = "12:00"}
nl_547 = {route = "500", time = "13:00"}
nl_551 = {route = "500", time = "14:00"}
nl_555 = {route = "500", time = "15:00"}
nl_559 = {route = "500", time = "16:00"}
nl_563 = {route = "500", time = "17:00"}
nl_567 = {route = "500", time = "18:00"}
nl_571 = {route = "500", time = "19:00"}
nl_575 = {route = "500", time = "20:00"}
nl_579 = {route = "500", time = "21:00"}
nl_583 = {route = "500", time = "22:00"}
nl_587 = {route = "500", time = "23:00"}
nl_591 = {route = "500", time = "24:00", end_at = "nl_amf"}
